# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: Build
  trigger:
  - master
  - dev
  pr:
  - dev
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'


jobs:
- job: Deploy
  trigger:
  - master
  pr:
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        git checkout $(Build.SourceBranchName)
        git remote add heroku https://heroku:$(pat)@git.heroku.com/taxcalculatorzpi.git
        git push -f heroku $(Build.SourceBranchName)


# SonarCloud task to fix
# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'Code analyse'
#     organization: '9d6dd48e270fd2af5f82926e090b08c6c51d1a49'
#     scannerMode: 'MSBuild'
#     projectKey: 'BornedInKwartannaAnalysis'