# Node.js with React

# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:$(pat)@git.heroku.com/taxcalculatorzpi.git
      git push heroku $(Build.SourceBranchName)

# Build a Node.js project that uses React.
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
