export const taxstate = [
  {
    name: "Georgia",
    base: 0.04,
    total: 0.08,
    groceries: 0.04,
    preparedFood: null,
    prescriptionDrug: null,
    nonPrescriptionDrug: null,
    clothing: null,
    intangibles: null,
  },
  {
    name: "Alaska",
    base: 0.0,
    total: 0.07,
    groceries: null,
    preparedFood: null,
    prescriptionDrug: null,
    nonPrescriptionDrug: null,
    clothing: null,
    intangibles: null,
  },
  {
    name: "Colorado",
    base: 0.029,
    total: 0.1,
    groceries: 0.04,
    preparedFood: null,
    prescriptionDrug: null,
    nonPrescriptionDrug: null,
    clothing: null,
    intangibles: null,
  },
];
